### ISSUE TITLE
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'value')

### ISSUE THREAD

**Issue by NoahZuo** [SamboyCoding/UnityMemorySnapshotThing#1]
While using this tool to read my snapshot file, an exception has just raised: 

 > Processing 417 GC roots...
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'value')
   at UMS.Analysis.Structures.Objects.ComplexFieldValue..ctor(SnapshotFile file, BasicFieldInfoCache info, Nullable`1 parent, Span`1 data, Int32 depth, LoadedReason loadedReason) in I:\Snapshot\UnityMemorySnapshotThing\UMS.Analysis\Structures\Objects\ComplexFieldValue.cs:line 33
   at UMS.Analysis.Structures.Objects.IFieldValue.Read(SnapshotFile file, BasicFieldInfoCache info, Span`1 fieldData, Int32 depth, LoadedReason loadedReason, Nullable`1 parent) in I:\Snapshot\UnityMemorySnapshotThing\UMS.Analysis\Structures\Objects\IFieldValue.cs:line 56
   at UMS.Analysis.Structures.Objects.ManagedClassInstance.ReadFieldValue(SnapshotFile file, BasicFieldInfoCache info, Span`1 fieldData, Int32 depth, LoadedReason loadedReason) in I:\Snapshot\UnityMemorySnapshotThing\UMS.Analysis\Structures\Objects\ManagedClassInstance.cs:line 153
   at UMS.Analysis.Structures.Objects.ManagedClassInstance.ReadFields(SnapshotFile file, Span`1 data, Int32 depth) in I:\Snapshot\UnityMemorySnapshotThing\UMS.Analysis\Structures\Objects\ManagedClassInstance.cs:line 146
   at UMS.Analysis.Structures.Objects.ManagedClassInstance..ctor(SnapshotFile file, RawManagedObjectInfo info, Nullable`1 parent, Int32 depth, LoadedReason loadedReason, Int32 fieldIndexOrArrayOffset) in I:\Snapshot\UnityMemorySnapshotThing\UMS.Analysis\Structures\Objects\ManagedClassInstance.cs:line 116
   at UMS.Analysis.SnapshotFile.GetOrCreateManagedClassInstance(UInt64 address, Nullable`1 parent, Int32 depth, LoadedReason reason, Int32 fieldOrArrayIdx) in I:\Snapshot\UnityMemorySnapshotThing\UMS.Analysis\SnapshotFile.cs:line 120
   at UMS.Analysis.SnapshotFile.LoadManagedObjectsFromGcRoots() in I:\Snapshot\UnityMemorySnapshotThing\UMS.Analysis\SnapshotFile.cs:line 61
   at UnityMemorySnapshotThing.Program.Main(String[] args) in I:\Snapshot\UnityMemorySnapshotThing\UnityMemorySnapshotThing\Program.cs:line 57

How to fix this issue please?

**Comment by SamboyCoding** [comment]
What version of unity?
